{% set version = "2.0.1" %}

package:
  name: pwlf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pwlf/pwlf-{{ version }}.tar.gz
  sha256: 89d1f92b67b3670d135042da32a6a9752d0948e511b081f162f5fef4164920e7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pydoe >=0.3.8
    - numpy
    - scipy >=1.2.0
    - setuptools

test:
  imports:
    - pwlf

about:
  home: https://github.com/cjekel/piecewise_linear_fit_py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'fit piecewise linear data for a specified number of line segments '

  description: |
    A library for fitting continuous piecewise linear functions to data.
    Just specify the number of line segments you desire and provide the data.
  doc_url: https://jekel.me/piecewise_linear_fit_py/
  dev_url: https://github.com/cjekel/piecewise_linear_fit_py

extra:
  recipe-maintainers:
    - h-vetinari
